#ifndef __DEPRECATE_ALL_RINGBUS_H__
#define __DEPRECATE_ALL_RINGBUS_H__

/// Include this file to undefine all ringbus we have stopped using
///
/// make this file with:
///
/// cat c/inc/ringbus.h | grep DEPRECATED | sed -e 's/#define \([^ ]*\) \(.*\)/#undef \1/'
///


#undef CS11_PROGRESS_CMD
#undef CS02_PROGRESS_CMD
#undef CS20_PROGRESS_CMD
#undef RESET_LIFETIME_CMD
#undef ADD_LIFETIME_CMD
#undef SCHEDULE_EPOC_CMD
#undef CS02_REPORT_ERRORS_CMD
#undef CS11_REPORT_ERRORS_CMD
#undef CS20_REPORT_ERRORS_CMD
#undef CS20_MAIN_REPORT_STATUS_CMD
#undef CS02_MAIN_REPORT_STATUS_CMD
#undef CS11_MAIN_REPORT_STATUS_CMD
#undef CS11_SET_GAIN_CMD
#undef CS21_DEMOD_MODE
#undef CS21_CHOOSE_CUSTOM_SC_CMD
#undef CS10_ENABLE_MAG_CHECK
#undef CS01_ENABLE_MAG_CHECK
#undef LIFETIME_TO_EPOC_CMD
#undef RX_CS00_ERROR_PCCMD
#undef RX_CS21_DID_ADJUST
#undef CS20_EPOC_REPORT_PCCMD
#undef CS02_EPOC_REPORT_PCCMD
#undef CS11_EPOC_REPORT_PCCMD
#undef CS20_PROGRESS_REPORT_PCCMD
#undef CS02_PROGRESS_REPORT_PCCMD
#undef CS11_PROGRESS_REPORT_PCCMD
#undef CS01_MAG_CHECK_PCCMD
#undef CS10_MAG_CHECK_PCCMD
#undef CS20_USERDATA_ERROR
#undef CS02_USERDATA_ERROR
#undef CS11_USERDATA_ERROR
#undef EPOC_REPLY_PCCMD
#undef CS20_FILL_LEVEL_PCCMD
#undef CS02_FILL_LEVEL_PCCMD
#undef CS11_FILL_LEVEL_PCCMD
#undef TX_FILL_LEVEL_PCCMD
#undef CS11_FB_REPORT_PCCMD
#undef CS02_FB_REPORT_PCCMD
#undef CS20_FB_REPORT2_PCCMD
#undef CS02_FB_REPORT2_PCCMD
#undef CS11_FB_REPORT2_PCCMD
#undef CS20_REPORT_STATUS_PCCMD
#undef CS02_REPORT_STATUS_PCCMD
#undef CS11_REPORT_STATUS_PCCMD


#endif
